# Generated by Django 3.0.5 on 2020-04-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
