# Generated by Django 3.0.5 on 2020-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0002_auto_20200422_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
